### ISSUE TITLE
../oberon doesn't exist

### ISSUE THREAD

**Issue by rafaelnogalha** [wh4tsername/Mini-Java-Compiler#4]
Hello, @wh4tsername. We tried to execute the test, but didn't function cause ../oberon doesn't exist. Could you help us with that?

**Comment by wh4tsername** [comment]
Hello, @rafaelnogalha. Thanks for pointing out this error, master branch was stale. Now I've updated it and merged IR branch with partial assembly support.

**Comment by wh4tsername** [comment]
Also I've rewritten README to make it more clear

**Comment by rafaelnogalha** [comment]
Hello, @wh4tsername ! Thank you, we will try to execute again!
